-- FIND THE AVERAGE SHIPPINNG DURATION  IN DAYS FOR EACH MONTH
SELECT
OrderID, OrderDate,
DATEDIFF(DAY, ORDERDATE, SHIPDATE) AS DAYSTOSHIP
FROM SALES.ORDERS;
-- 
SELECT
MONTH(OrderDate) MONTHS,
AVG(DATEDIFF(DAY, ORDERDATE, SHIPDATE) ) AS AVGSHIP
FROM SALES.ORDERS
GROUP BY MONTH(OrderDate)