-- HOW MANY ORDERS WERE PLACED EACH YEAR?
SELECT
YEAR (ORDERDATE),
COUNT (*) NO_OF_ORDERS
FROM SALES.ORDERS
GROUP BY YEAR (ORDERDATE);
-- HOW MANY ORDERS WERE PLACED EACH MONTH??
SELECT
MONTH(ORDERDATE),
COUNT (*) NO_OF_ORDERS
FROM SALES.ORDERS
GROUP BY MONTH(ORDERDATE);
-- HOW MANY ORDERS WERE PLACED EACH DAY?
SELECT
DAY(ORDERDATE),
COUNT(*) NO_OF_ORDERS
FROM SALES.ORDERS
GROUP BY DAY(ORDERDATE);