-- Part extraction for the YEAR, MONTH, DATE, DATEPART(DP) HOUR, QUARTER, WEEK, DATENAME(DN), DATETRUNC(DC)
select
OrderID,
creationtime,
--DATETRUNC EXAMPLES
DATETRUNC(MINUTE, CREATIONTIME) AS MIN_DT,
DATETRUNC(DAY, CREATIONTIME) AS DAY_DT,
--DATENAME EXAMPLES
DATENAME(MONTH, CREATIONTIME) AS MONTH_DPDN,
DATENAME(WEEK, CREATIONTIME) AS WEEK_DPDN,
DATENAME(DAY, CREATIONTIME) AS DAY_DPDN,
--DATEPART EXAMPLES
DATEPART (YEAR, CREATIONTIME) AS YEAR_DP,
DATEPART(MONTH, CREATIONTIME) AS MONTH_DP,
DATEPART(DAY, CREATIONTIME) AS DAY_DP,
DATEPART(HOUR, CREATIONTIME) AS HOUR_DP,
DATEPART(QUARTER, CREATIONTIME) AS QUARTER_DP,
DATEPART(WEEK, CREATIONTIME) AS WEEK_DP,
YEAR (CreationTime) year,
MONTH (CreationTime) month,
DAY (CreationTime) day
from
sales.orders