-- TIME GAP ANALYSIS
-- FIND THE NO. OF DAYS BETWEEN EACH ORDER AND PREVIOUS ORDER
SELECT
ORDERID,
ORDERDATE AS CURRENT_ORDERDATE,
LAG(ORDERDATE) OVER (ORDER BY ORDERDATE) PREVIOUS_ORDER_DATE,
DATEDIFF(DAY, LAG(ORDERDATE) OVER (ORDER BY ORDERDATE), ORDERDATE) NROFDAYS
FROM SALES.Orders