-- END OF THE MONTH USES
SELECT
ORDERID,
CREATIONTIME,
EOMONTH (CREATIONTIME) END_OF_MONTH,
--WHAT IF WE NEED TO KNOW THE FIRST DATE OR START OF THE MONTH SO USE THIS
CAST (DATETRUNC (MONTH, CREATIONTIME) AS DATE) START_OF_MONTH
FROM SALES.ORDERS