-- FIND THE TOTAL SALES ACROSS ALL ORDERS
SELECT
SUM (SALES) AS TOTAL_SALES
FROM
SALES.Orders;

-- FIND THE TOTAL SALES FOR EACH PRODUCT
SELECT PRODUCTID,
SUM (SALES) AS TOTAL_SALES
FROM
SALES.Orders
GROUP BY ProductID