/* FIND THE TOTAL SALES FOR EACH PRODUCT,
ADDITIONALLY PROVIDE DETAILS SUCH AS ORDERID, ORDER DATE */
SELECT 
        OrderID,
		OrderDate,
		-- BY PUTTING ORDERID AND ORDERDATE WE CANNOT GET DESIRED RESULT BY USIGN (GROUP BY)
		-- ALL COULUMNS IN SELECT MUST BE INCLUDED IN GROUP BY
		PRODUCTID,
		SUM (SALES) AS TOTAL_SALES
		FROM
		SALES.Orders
GROUP BY 
         OrderID,
		 OrderDate,
         ProductID -- LIMITED USE OF GROUP BY FUNCTION
