-- SHOW ALL ORDERS THAT WERE PLACED DURING THE MONTH OF FEBRUARY
SELECT *
FROM SALES.ORDERS
WHERE MONTH(ORDERDATE) = 2;
-- OTHER THAN FEBRUARY
SELECT *
FROM SALES.ORDERS
WHERE MONTH(ORDERDATE) != 2;
--NOTE-FILTERING THE DATA USING AN INTEGER IS FASTER THAN USING A STRING
