--USING SUBQUERIES WITH THE FROM CLAUSE
/*TASK: FIND THE PRODUCTS THAT HAVE A PRICE 
       HIGHER THAN AVERAGE PRICE OF ALL PRODUCTS*/
--MAIN QUERY
SELECT
*
FROM (
        --SUBQUERY
        SELECT
        PRODUCTID,
        PRICE,
        AVG(PRICE) OVER () AVG_PRICE
        FROM SALES.Products
        )T
        WHERE PRICE > AVG_PRICE