--USE OF CONVERT
SELECT
CONVERT(INT, '123') AS [STRING TO INT CONVERT],
CONVERT(DATE, '2025-08-20') AS [STRING TO DATE CONVERT],
CREATIONTIME,
CONVERT(DATE, CREATIONTIME) AS [DATETIME TO DATE CONVERT],
CONVERT(VARCHAR, CREATIONTIME) AS [USED AS CONVERT INSTEAD OF FORMAT]
FROM SALES.ORDERS
