--WINDOW 2 PRECEDING AND CURRENT ROW OR ROWS 2 PRECEDING 
SELECT
ORDERID,
ORDERDATE,
ORDERSTATUS,
SALES,
SUM (SALES) OVER (PARTITION BY ORDERSTATUS ORDER BY ORDERDATE 
             ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)-- DEFAULT WINDOW SETTING / OR JUST WRITE UNBOUNDED PRECEDING 
             FROM
        SALES.Orders