--  RANK CUSTOMER BASED ON THEIR TOTAL SALES AND -- HERE WHAT IS THAT WE CANNOT USE RANK BY WITH GROUP BY
--FOR THE RANK WINDOW FN -- FOR THE SALES GROUP BY
--WINDOW FN CAN BE USED TOGETHER WITH GROUP BY IN THE SAMEK QUERY ONLY IF THE SAME COLUMNS  ARE USED..4
SELECT  
CUSTOMERID,
SUM (SALES) TOTALSALES,
RANK() OVER (ORDER BY SUM(SALES) DESC ) RANKCUSTOMER
FROM SALES.Orders
GROUP BY CustomerID