--WINDOW 2 PRECEDING AND CURRENT ROW OR ROWS 2 PRECEDING 
SELECT
ORDERID,
ORDERDATE,
ORDERSTATUS,
SALES,
SUM (SALES) OVER (PARTITION BY ORDERSTATUS ORDER BY ORDERDATE 
                  ROWS  2 PRECEDING   ) TOTALSALES
    FROM
        SALES.Orders