-- FIND THE TOTAL SALE ACROSS ALL ORDERS 
-- ADDITIONALY PROVIDE DETAIL SUCH AS ORDERID AND ORDERDATE

SELECT
ORDERID,
ORDERDATE,
PRODUCTID,
ORDERSTATUS,
Sales,
SUM(SALES) OVER () TOTALSALES, -- FINDING THE TOTAL SCORE 
SUM(SALES) OVER (PARTITION BY PRODUCTID) TOTALSALESBYPRODUCT, -- WINDOW IS CONTROLLED BY (PRODUCTID)
SUM(SALES) OVER ( PARTITION BY PRODUCTID, ORDERSTATUS) SALESBYPRODUCTandSTATUS --COMBINATION OF PRODUCT AND ORDER STATUS
FROM SALES.Orders
-- DIFFERENT GRANULARTIES WITHIN SAME QUERIES