-- DUE TO DATA QUALITY ISSUE COUNT() CAN BE USED TO IDENTIFY DUBLICATES
-- CHECK WETHER THE TABLE 'ORDERS' CONTAIN ANY DUBLICATE ROWS
SELECT
COUNT(*) OVER (PARTITION BY ORDERID) CHECKPK
FROM SALES.Orders