-- RANK EACH ORDER BASED ON THEIR SALES FROM HIGHEST TO LOWEST
--ADDITIONALLY PROVIDE DETAILS SUCH AS ORDER ID, ORDER DATE
SELECT
      ORDERID,
      ORDERDATE,
      Sales,
 RANK() OVER (ORDER BY SALES) RANKSALES
FROM
     SALES.Orders