--IDENTIFY DUBLICATE ROWS IN THE TABLE 'ORDER ARCHIVE'
-- AND RETURN A CLEAN RESULT WITHOUT ANY DUBLICATES
SELECT * FROM (
SELECT
ROW_NUMBER() OVER (PARTITION BY ORDERID ORDER BY CreationTime desc)rn,
*
FROM SALES.OrdersArchive
)T
WHERE rn = 1