--FIND THE LOWEST TWO CUSTOMER BASED ON THEIR TOTAL SALES (BOTTOM N ANALYSIS)
SELECT *
FROM (
SELECT
CUSTOMERID,
SUM(Sales) TOTALSALES,
ROW_NUMBER() OVER(ORDER BY SUM(SALES)) RANKCUSTOMERS
FROM
SALES.Orders
GROUP BY 
CustomerID
)T
WHERE RANKCUSTOMERS <= 2