SELECT
ORDERID,
ORDERDATE,
ORDERSTATUS,
SALES,
SUM (SALES) OVER (PARTITION BY ORDERSTATUS ORDER BY ORDERDATE 
                  ROWS BETWEEN CURRENT ROW AND 2 FOLLOWING ) TOTALSALES
    FROM
        SALES.Orders