-- SQL EXECUTE WINDOW FN AFTER WHERE CLAUSE..3
SELECT
ORDERID,
ORDERDATE,
OrderStatus,
ProductID,
Sales,
SUM(SALES) OVER (PARTITION BY ORDERSTATUS) TOTALSALES
FROM
SALES.Orders
WHERE ProductID IN  (101 , 102)