--FIND THE TOP HIGHEST SALES FOR EACH PRODUCT(TOP N ANALYSIS)
SELECT *
FROM    (SELECT 
		ORDERID,
		PRODUCTID,
		SALES,
		ROW_NUMBER () OVER(PARTITION BY PRODUCTID ORDER BY SALES DESC) RankByProduct
		FROM SALES.Orders
)T
WHERE RankByProduct = 1