--WINDOW FUNCTION 4X RULE
--CAN ONLY BE USED IN SELECT AND ORDER BY CLAUSES...1
--NESTING WINDOW FUNCTION IS NOT ALLOWED...2
SELECT
ORDERID,
ORDERDATE,
OrderStatus,
Sales,
SUM(SALES) OVER (PARTITION BY ORDERSTATUS) TOTALSALES
FROM
SALES.Orders
ORDER BY SUM(SALES) OVER (PARTITION BY ORDERSTATUS) DESC-- CANNOT USE WHERE CLAUSES HERE IN WINDOW FN TO FILTER DATA